[package]
name = "ai"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = { version = "0.35.0", features = ["serde-serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2.127"

[lib]
crate-type = ["cdylib", "rlib"]
# Caused by: crate-type must be cdylib to compile toWebAssembly. Add the following to your Cargo.toml file:
