[package]
name = "ai"
version = "0.1.0"
edition = "2024"

[dependencies]
getrandom = { version = "0.4", features = ["wasm_js"] }
rand = "0.10"
wasm-bindgen = "0.2.127"

[lib]
crate-type = ["cdylib", "rlib"]
# Caused by: crate-type must be cdylib to compile toWebAssembly. Add the following to your Cargo.toml file:
